patterns = {
    '[àáảãạăắằẵặẳâầấậẫẩ]': 'a',
    '[đ]': 'd',
    '[èéẻẽẹêềếểễệ]': 'e',
    '[ìíỉĩị]': 'i',
    '[òóỏõọôồốổỗộơờớởỡợ]': 'o',
    '[ùúủũụưừứửữự]': 'u',
    '[ỳýỷỹỵy]': 'i'
}

list_jobs = {
    'tu van': 'BH',
    'duoc ta': 'BS',
    'ktv': 'KTV',
    'thu qui': 'KT',
    'can su' : 'CB',
    'chu tich': 'GD',
    'van thu': 'NV',
    'truong bo phan': 'QL',
    'cong chuc': 'CB',
    'pho truong': 'CB',
    'bac si': 'BS',
    'dien vien': 'DV',
    'to truong': 'QL',
    'chi hui': 'QL',
    'to truong': 'QL',
    'lap trinh vien': 'KTV',
    'kien truc su': 'KTV',
    'giao dich': 'CV',
    'kien truc': 'KS',
    'thu i': 'BS',
    'bac si': 'BS',
    'huan luien': 'KTV',
    'vien': 'KTV',
    'thu mua': 'BH',
    'thuong truc': 'CB',
    'van thu': 'CB',
    'sales': 'BH',
    'bien tap': 'NV',
    'truong': 'QL',
    'phu xe': 'LX',
    'staff' : 'NV',
    'nau an': 'NV',
    'quai ghi' : 'KT',
    'cua hang' : 'NV',
    'i te' : 'BS',
    'tap vu' : 'NV',
    'phu bep' : 'NV',
    'thu ngan' : 'NV',
    'le tan' : 'NV',
    'kiem ngan' : 'KT',
    'cu nhan' : 'KS',
    'phu trach' : 'QL',
    'bep pho' : 'QL',
    'to pho' : 'QL',
    'i ta' : 'BS',
    'thui thu' : 'CB',
    'hieu pho': 'CB',
    'tham phan' : 'CB',
    'thu ki' : 'CB',
    'bep chinh' : 'QL',
    'phu' : 'NV',
    'doi vien' : 'CB',
    'k? s?' : 'KS',
    'pho ct' : 'GD',
    'xe' : 'LX',
    'checker' : 'KT',
    'c.nhan' : 'CN',
    'nhan vien': 'NV',
    'giom sot' : 'GS',
    'cham soc' : 'NV',
    'gs': 'GS',
    'cv' : 'CV',
    'nhan ven' : 'NV',
    'co nuoi' : 'LD',
    'con b?' : 'LD',
    'chuien doanh' : 'BH',
    'chuiªn viªn' : 'CV',
    'marketing' : 'BH',
    'chu nhiem' : 'GV',
    'c.n' : 'CN',
    'gv' : 'GV',
    'xa doi': 'CB',
    'dai dien': 'CB',
    'worker' : 'CN',
    'xai dung' : 'DV',
    'kinh doanh' : 'BH',
    'cong nghiep' : 'CN',
    'ldhd' : 'LD',
    'han dien' : 'LD',
    'chuion vion': 'CV',
    'nhon vion' : 'NV',
    'thu cong': 'LD',
    'khai thac' : 'LD',
    'dao tao' : 'KTV',
    'ke hoach' : 'NV',
    've sinh' : 'LD',
    'don tiep' : 'DV',
    'dd' : 'BH',
    'giao hang': 'BH',
    'ien tiec': 'DV',
    'barista': 'NV',
    'dich vu' : 'DV',
    'dieu hanh': 'QL',
    'tong dai': 'DV',
    'in': 'DV',
    'it' : 'BS',
    'tiep thi' : 'BH',
    'cung nhon' : 'CN',
    'phien dich': 'KTV',
    'giao nhan' : 'DV',
    'det' : 'LD',
    'hanh chinh' : 'CB',
    'qc' : 'DV',
    'dung bep' : 'NV',
    'thu viec' : 'NV',
    'tap su' : 'NV',
    'cap duong' : 'NV',
    'ca si' : 'LD',
    'coong nhaon' : 'CN',
    'phet keo' : 'CN',
    'thi nghiem' : 'KT',
    'thanh tra' : 'CB',
    'don hang' : 'DV',
    'mai' : 'LD',
    'bao ve' : 'NV',
    'b?o v?' : 'NV',
    've si' : 'DV',
    'det' : 'LD',
    'ld' : 'LD',
    'ql' : 'QL',
    'gia cong' : 'LD',
    'co khi' : 'CN',
    'trien khai' : 'VH',
    'nau bep' : 'CN',
    'dv' : 'DV',
    'nhon' : 'CN',
    'lao cong' : 'LD',
    'luu hoa' : 'BH',
    'lap rap' : 'KT',
    'thi cong' : 'KT',
    'xd' : 'DV',
    'llqs' : 'CB',
    'bao tri' : 'KT',
    'to chuc' : 'CB',
    'doan thanh nien': 'CB',
    'dong goi': 'DV',
    'kiem gap' : 'DV',
    'cod' : 'DV',
    'ho sinh' : 'LD',
    'tiep thuc' : 'DV',
    'bao tri' : 'NV',
    'ho tro' : 'DV',
    'd. goi': 'DV',
    'van hoa' : 'CB',
    'lai mau' : 'CN',
    'ks' : 'KS',
    'quan doanh' : 'CB',
    'bao duong': 'DV',
    'kiem tra' : 'DV',
    'hang rong' : 'LD',
    'kho qui' : 'QL',
    'pgd' : 'GD',
    'lao d?ng' : 'LD',
    'kho' : 'QL',
    'bhxh' : 'DV',
    'n.v' : 'NV',
    'cong  nhan' : 'CN',
    'c. nhan': 'CN',
    'kiom tra' : 'KT',
    'kiem pham' : 'KT',
    'qui': 'QL',
    'i' : 'BS',
    'mia' : 'CN',
    'phat hanh' : 'DV',
    'pho phong' : 'QL',
    'pha che' : 'LD',
    'ho li' : 'DV',
    'nhaon vieon' : 'NV',
    'pbt' : 'CB',
    'ltv' : 'KTV',
    'thiet ke' : 'KTV',
    'doi pho' : 'QL',
    'tc' : 'CB',
    'don  tiep' : 'DV',
    'khung sat' : 'LD',
    'kt' : 'KT',
    'dan toc' : 'CB',
    'cd' : 'NV',
    'cb' : 'CB',
    'truỏng': 'QL',
    'che bien' : 'DV',
    'ui' : 'CB',
    'ep cao tan':'LD',
    'truc buong' : 'BS',
    'phim' : 'KT',
    'duoc' : 'BS',
    'mvc' : 'LD',
    'bep' : 'CN',
    'cn' : 'CN',
    'nv' : 'CN'
    }

list_46 = {
    ('c.ti', 'cong ti', 'tnhh','ct', 'xn', 'xi nghiep', 'nhtmcp', 'nha mai', 'vien thong', 'dn', 'tm cp', 'congti', 'co phan', 'vinatea'): 'CTY',
    ('dan toc', 'khang chien', 'phong noi vu', 'pnv', 'can bo', 'doi tuong', 'cach mang', 'chien binh', 'cu dan', 'huien', 'xa', 'phuong', 'ban chap hanh', 'bch', 'thanh nien', 'ban', 'nong dan', 'dtts', 'htx', 'ban', 'nd', 'tre em', 'quan li', 'nguoi huong', 'nguoi dan', 'huong tro cap', 'si quan', 'hssv', 'nhan dan', 'nguoi co cong', 'cong an', 'bql', 'gia dinh', 'con nguoi', 'hoi nguoi', 'clb', 'hoi', 'hoi dong', 'hd', 'dan quan', 'mat suc'): 'ND',
    ('trung tam', 'tt', 'chi cuu thue','bhit', 'bhxh', 'bao hiem xa hoi', 'buu dien', 'co so', 'chi cuc', 'cuc thong ke', 'dau tu', 'phong', 'dai phat thanh', 'cap the', 'vpdd', 'cum', 'cuc', 'so', 'bao', 'trung doan','nha hat', 'nha khach', 'vien nghien cuu','kho bac', 'vien', 'lien doan','dang ui', 'tinh doan', 'hang khong', 'hang hai', 'to chuc', 'vp', 'doan bai'): 'TT',
    ('ngan hang', 'tai chinh', 'du an', 'qui', 'huu tri'): 'TC',
    ('benh vien', 'bv', 'i te', 'pk dk'): 'BV',
    ('chi nhanh', 'khach san', 'dai li', 'dl', 'hotel'): 'DL',
    ('hoc vien', 'mam non', 'dai hoc', 'tieu hoc', 'thcs', 'mau giao', 'cao dang', 'thpt', 'dh', 'trung cap', 'truong', 'th', 'giao duc', 'dao tao', 'nha tre'): 'TH',
    ('hkd', 'ho kd', 'ho kinh doanh', 'tu nhan', 'tn', 'ho gia dinh', 'hgd', 'ho gd', 'hieu', 'chan nuoi'): 'HGD',
    ('kk', 'ngheo', 'kho khan', 'nghèo'): 'HN'
}    

missing_value = "missing"

list_drop_field_train = ["Field_11", "Field_3", "Field_4", "Field_13", "Field_14", "Field_24", "Field_25", "Field_26", "Field_30", "Field_31","Field_42", 
 "Field_35", "Field_51", "Field_52", "Field_55","Field_56", "Field_57", "Field_59", "Field_61", "diaChi", "namSinh", "Field_16", "Field_17"]

list_drop_field_test = ["Field_11", "Field_3", "Field_4", "Field_13", "Field_14", "Field_24", "Field_25", "Field_26", "Field_30", "Field_31","Field_42", 
 "Field_35", "Field_51", "Field_52", "Field_55","Field_56", "Field_57", "Field_59", "Field_61", "diaChi", "namSinh", "Field_16", "Field_17",
 "Field_65", "Field_48"]

list_date_field = ["Field_1", "Field_2", "Field_5","Field_6", "Field_7", "Field_8","Field_9", "Field_15", "Field_32", "Field_33","Field_40", "Field_43", "Field_44",
                   "Field_34", "F_startDate","F_endDate", "E_startDate","E_endDate", 
                   "C_startDate","C_endDate","G_startDate","G_endDate","A_startDate","A_endDate"]

list_date_field_start = ["F_startDate", "E_startDate", "C_startDate", "G_startDate", "A_startDate"]
list_date_field_end = ["F_endDate", "E_endDate", "C_endDate", "G_endDate", "A_endDate"]
list_date_field_alone = ["Field_1", "Field_2", "Field_5","Field_6", "Field_7", "Field_8","Field_9", "Field_15", "Field_32", "Field_33","Field_40", "Field_43", "Field_44",
                   "Field_34"]

def get_all_province():
    import json

    result = []
    with open("district.json", 'r') as j:
        contents = json.loads(j.read())
        for province_code in contents:
            result.append(contents[province_code]['name'].lower())
    
    return result 

def get_cities_by_province(province):
    import json

    result = []
    with open("district.json", 'r') as j:
        contents = json.loads(j.read())
        for province_code in contents:
            if province == contents[province_code]['name'].lower():
                for city in contents[province_code]["cities"]:
                    result.append(contents[province_code]["cities"][city].lower())

    return result 
